/**
 * CRONOGRAMA EDITORIAL OFICIAL MULTIMARCAS (104 POSTS)
 * Período: 07 de Setembro a 27 de Dezembro de 2026 (16 semanas)
 * Metas Contratuais Flexíveis (Distribuição Aleatória / Não Fixa):
 * - Steelfish: 32 posts (2x por semana em dias variados e aleatórios)
 * - Fishing Company: 32 posts (2x por semana em dias variados e aleatórios)
 * - TR Fishing: 16 posts (1x por semana em dias variados e aleatórios)
 * - Iscas Mathias: 16 posts (1x por semana em dias variados e aleatórios)
 * - Titan Caiaques: 8 posts (2x por mês em dias variados e aleatórios)
 * Datas Sazonais: Primavera (22/09), Dia das Crianças (12/10), Black Friday (23-30/11), Natal & Verão (Dezembro)
 */
window.OFFICIAL_INSTAGRAM_104_POSTS = [
  {
    "date": "2026-09-07",
    "dayOfWeek": "Segunda-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Proteção & Saúde",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nCamisas UV50+: Por Que o Pescador Não Pode Negligenciar o Sol do Meio-Dia\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "published",
    "id": "insta-104-001"
  },
  {
    "date": "2026-09-08",
    "dayOfWeek": "Terça-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nAtaque na Superfície: Stick vs Zara nos Bicos de Foz do Areia\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "published",
    "id": "insta-104-002"
  },
  {
    "date": "2026-09-10",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Credibilidade & Logística",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nBastidores do Despacho: Como Embalamos seus Pedidos com Segurança\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "published",
    "id": "insta-104-003"
  },
  {
    "date": "2026-09-11",
    "dayOfWeek": "Sexta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Lifestyle Outdoor",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nSábado no Lago: Conforto Térmico da Saída ao Pôr do Sol\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "published",
    "id": "insta-104-004"
  },
  {
    "date": "2026-09-12",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Técnicas de Iscas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nTrabalho Lento de Meia-Água para Dias de Vento Frio\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "ready",
    "id": "insta-104-005"
  },
  {
    "date": "2026-09-13",
    "dayOfWeek": "Domingo",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Dicas Técnicas",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nNó FG Perfeito em Menos de 60 Segundos para Linha Multifilamento\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "ready",
    "id": "insta-104-006"
  },
  {
    "date": "2026-09-14",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Catálogo & Destaques",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nCatálogo Iscas Mathias: As Cores Mais Pedidas da Semana\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-007"
  },
  {
    "date": "2026-09-15",
    "dayOfWeek": "Terça-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Dicas de Iscas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nGuia de Cores: Osso, Cromada ou Transparente em Água Limpa?\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-008"
  },
  {
    "date": "2026-09-16",
    "dayOfWeek": "Quarta-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Manutenção & Durabilidade",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nManutenção Preventiva de Carretilhas: Lubrificação Básica sem Abrir Tudo\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-009"
  },
  {
    "date": "2026-09-17",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Equipamento",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nExplosão de Bocudo: Teste do Drag da Carretilha Steelfish\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-010"
  },
  {
    "date": "2026-09-18",
    "dayOfWeek": "Sexta-feira",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "reels",
    "pillar": "Alta Performance & Engenharia",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nTitan Caiaques: Engenharia Náutica e Máxima Estabilidade em Pé\n\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-011"
  },
  {
    "date": "2026-09-19",
    "dayOfWeek": "Sábado",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Moda & Performance",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nPrimavera Chegando: Cores Vivas e Estampas Exclusivas da Fishing Co.\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-012"
  },
  {
    "date": "2026-09-20",
    "dayOfWeek": "Domingo",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Tecnologia Têxtil",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nTecnologia Dry Fit Antibacteriana: Como Funciona no Calor Extremo\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-013"
  },
  {
    "date": "2026-09-21",
    "dayOfWeek": "Segunda-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Linhas & Equipamentos",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nGuia de Bitolas: 20lb, 30lb ou 40lb? Qual Escolher para Tucunaré?\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-014"
  },
  {
    "date": "2026-09-22",
    "dayOfWeek": "Terça-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Sazonalidade",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nInício da Primavera: O Uniforme Oficial da Temporada de Pesca\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-015"
  },
  {
    "date": "2026-09-23",
    "dayOfWeek": "Quarta-feira",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "feed",
    "pillar": "Tecnologia & Ação",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nPedal Sistema Mecânico: Navegação Silenciosa sem Espantar os Cardumes\n\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-016"
  },
  {
    "date": "2026-09-24",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nPrimavera dos Tucunarés: Acelere o Recolhimento na Superfície\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-017"
  },
  {
    "date": "2026-09-25",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Técnicas de Iscas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nPausa Provocadora: O Segredo para Peixe Manhoso\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-018"
  },
  {
    "date": "2026-09-26",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Agilidade & Confiança",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nEntrega Expressa para Todo o Brasil: Do Nosso Estoque para a sua Tralha\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-019"
  },
  {
    "date": "2026-09-27",
    "dayOfWeek": "Domingo",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Proteção Solar",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nMuv & Bandana: Proteção Total para Rosto, Pescoço e Orelhas\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-020"
  },
  {
    "date": "2026-09-28",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Catálogo & Dicas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nTop 3 Iscas Steelfish que Não Podem Faltar no Estojo\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-021"
  },
  {
    "date": "2026-09-29",
    "dayOfWeek": "Terça-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Qualidade de Produto",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nTestadas e Aprovadas: O Nado Irresistível das Iscas Artesanais Mathias\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-022"
  },
  {
    "date": "2026-09-30",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Ação & Lifestyle",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nSábado de Troféus: Como a Liberdade de Movimento Faz a Diferença no Arremesso\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-023"
  },
  {
    "date": "2026-10-01",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Equipamento & Alta Performance",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nCarretilha Steelfish: Lançamento Preciso nas Estruturas Submersas\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-024"
  },
  {
    "date": "2026-10-03",
    "dayOfWeek": "Sábado",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Equipamento & Conforto",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nJaqueta Corta-Vento Repelente à Água para Navegação Rápida\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-025"
  },
  {
    "date": "2026-10-04",
    "dayOfWeek": "Domingo",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Dicas Rápidas",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nComo Desembaraçar Cabeleiras sem Cortar a Linha Multifilamento\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-026"
  },
  {
    "date": "2026-10-05",
    "dayOfWeek": "Segunda-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Família & Lifestyle",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nDia das Crianças com a Família no Eldorado Lake: Roupa Certa para os Pequenos\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-027"
  },
  {
    "date": "2026-10-06",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Comparativo Técnico",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nNó SF vs Nó Albright: Qual Suporta Mais Carga de Arrasto?\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-028"
  },
  {
    "date": "2026-10-07",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Família & Crianças",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nLinha Kids UV50+: Protegendo as Crianças no Dia das Crianças e Finais de Semana\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-029"
  },
  {
    "date": "2026-10-08",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Prova Social",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nDepoimentos de Clientes: Fotos dos Troféus Pegos com Iscas Mathias\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-030"
  },
  {
    "date": "2026-10-09",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Dicas de Manuseio",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nAjuste de Freio Magnético para Evitar Cabeleira no Vento\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-031"
  },
  {
    "date": "2026-10-11",
    "dayOfWeek": "Domingo",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Esportividade & Família",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nDia das Crianças: Ensinando a Primeira Fisgada com Isca Artificial\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-032"
  },
  {
    "date": "2026-10-12",
    "dayOfWeek": "Segunda-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Acessórios Técnicos",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nLuvas de Pesca UV: Aderência Firme na Carretilha e Zero Bolhas\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-033"
  },
  {
    "date": "2026-10-13",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Técnica Subaquática",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nLíder de Fluorocarbono: O Segredo da Invisibilidade e Resistência à Abrasão\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-034"
  },
  {
    "date": "2026-10-14",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Tecnologia Têxtil",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nRespirabilidade em Ação: O Teste de Secagem Ultrarrápida\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-035"
  },
  {
    "date": "2026-10-15",
    "dayOfWeek": "Quinta-feira",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "reels",
    "pillar": "Aventura & Exploração",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nOutubro de Aventura: Explorando os Braços Secretos da Represa de Caiaque\n\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-036"
  },
  {
    "date": "2026-10-16",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nFisgada Firme: Como Evitar que o Tucunaré Escape no Pulo\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-037"
  },
  {
    "date": "2026-10-17",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Lançamentos",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nEstoque Renovado: Chegaram Novos Modelos de Iscas de Superfície\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-038"
  },
  {
    "date": "2026-10-18",
    "dayOfWeek": "Domingo",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Técnicas de Iscas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nIscas de Meia-Água com Rattlin: Quando Usar Vibração Sonora\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-039"
  },
  {
    "date": "2026-10-19",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Equipamento",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nDesafio na Galhada: Precisão Milimétrica com Carretilha Steelfish\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-040"
  },
  {
    "date": "2026-10-20",
    "dayOfWeek": "Terça-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Lifestyle & Rancho",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nPôr do Sol no Rancho: A Transição do Dia Quente para a Brisa Noturna\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-041"
  },
  {
    "date": "2026-10-21",
    "dayOfWeek": "Quarta-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Configuração de Carretilha",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nAjuste Fino do Freio Centrífugo: Como Configurar para Arremessos Longos\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-042"
  },
  {
    "date": "2026-10-22",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Consciência & Esporte",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nPesque e Solte: Como Manusear o Troféu com Alicate de Contenção\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-043"
  },
  {
    "date": "2026-10-24",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Dicas de Compra",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nComo Montar seu Kit de Iscas para Pescaria em Represas\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-044"
  },
  {
    "date": "2026-10-25",
    "dayOfWeek": "Domingo",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Praticidade Outdoor",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nBermudas e Calças Técnicas com Bolsos Multifuncionais para Iscas e Alicates\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-045"
  },
  {
    "date": "2026-10-26",
    "dayOfWeek": "Segunda-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Ferramentas do Pescador",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nAlicate de Bico Longo com Corte de Multifilamento: O Acessório Vital\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-046"
  },
  {
    "date": "2026-10-27",
    "dayOfWeek": "Terça-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Campanha Comercial",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nBlack Friday Steelfish: Os Maiores Descontos em Varas e Iscas\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-047"
  },
  {
    "date": "2026-10-28",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Campanha Comercial",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nBlack Friday Fishing Company: Roupas UV50+ com Descontos Históricos\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-048"
  },
  {
    "date": "2026-10-29",
    "dayOfWeek": "Quinta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Campanha Comercial",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nCyber Monday: Garanta seu Guarda-Roupa de Pesca para as Férias de Verão\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-049"
  },
  {
    "date": "2026-10-30",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Credibilidade",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nSegurança na Compra Online: Atendimento Humano e Suporte Rápido\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-050"
  },
  {
    "date": "2026-10-31",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Campanha Comercial",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nCyber Monday: Kits Exclusivos Steelfish para a Temporada de Verão\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-051"
  },
  {
    "date": "2026-11-01",
    "dayOfWeek": "Domingo",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "feed",
    "pillar": "Ergonomia & Design",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nEspaço de Carga e Conforto: Cadeira Ergonômica para 8 Horas de Pescaria\n\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-052"
  },
  {
    "date": "2026-11-02",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Técnicas de Iscas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nPopper Furioso: Como Criar o Borbulho Irresistível para os Grandes\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-053"
  },
  {
    "date": "2026-11-03",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Montagens & Iscas Soft",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nComo Prender o Anzol na Isca Soft sem Rasgar a Borracha\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-054"
  },
  {
    "date": "2026-11-04",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Proteção & Verão",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nDezembro Chegou: O Sol Mais Forte do Ano Exige Proteção Certificada UV50+\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-055"
  },
  {
    "date": "2026-11-06",
    "dayOfWeek": "Sexta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Organização & Dicas",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nMochila Estanque e Vestuário: Como Montar a Mala de Pesca Perfeita\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-056"
  },
  {
    "date": "2026-11-07",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Ofertas Especiais",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nPromoção Relâmpago de Quinta-Feira: Iscas Selecionadas no Site\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-057"
  },
  {
    "date": "2026-11-08",
    "dayOfWeek": "Domingo",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nÁgua Esquentando: Aumente o Tamanho da Isca de Superfície\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-058"
  },
  {
    "date": "2026-11-09",
    "dayOfWeek": "Segunda-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Campanha de Natal",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nNatal com Estilo: Roupas que Vão do Barco ao Churrasco com Amigos\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-059"
  },
  {
    "date": "2026-11-10",
    "dayOfWeek": "Terça-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Campanha de Natal",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nNatal no Lago: O Que Levar na Maleta de Iscas para as Férias\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-060"
  },
  {
    "date": "2026-11-11",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Campanha de Natal",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nPresente de Natal Inesquecível para o Pescador: Linha Fishing Company\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-061"
  },
  {
    "date": "2026-11-12",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Cuidados de Envio",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nEmbalagem Reforçada: Garantia de Tubos Protetores para Varas e Iscas\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-062"
  },
  {
    "date": "2026-11-13",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Campanha de Natal",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nPresente de Natal do Pescador: Varas e Carretilhas Steelfish\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-063"
  },
  {
    "date": "2026-11-14",
    "dayOfWeek": "Sábado",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "reels",
    "pillar": "Campanha Comercial",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nBlack Friday Titan Caiaques: Condições Especiais para Realizar seu Sonho\n\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-064"
  },
  {
    "date": "2026-11-15",
    "dayOfWeek": "Domingo",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Conservação",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nLimpeza Pós-Pescaria: Removendo Resíduos e Sujeira dos Passadores da Vara\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-065"
  },
  {
    "date": "2026-11-16",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Campanha Comercial",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nEsquenta Black Friday Iscas Mathias: Frete Grátis e Cupons Exclusivos\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-066"
  },
  {
    "date": "2026-11-17",
    "dayOfWeek": "Terça-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Férias & Aventura",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nFérias de Verão: O Kit Indispensável para 5 Dias Seguidos de Pescaria\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-067"
  },
  {
    "date": "2026-11-18",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Celebração & Lifestyle",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nAdeus 2026: Vista a Camisa dos Grandes Pescadores para o Novo Ano\n\nDestaque: Black Friday & Cyber Monday!\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-068"
  },
  {
    "date": "2026-11-19",
    "dayOfWeek": "Quinta-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Campanha Comercial",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nBlack Friday TR Fishing: Peças, Linhas e Ferramentas com Super Preços\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-069"
  },
  {
    "date": "2026-11-20",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nRetrospectiva dos Maiores Ataques do Ano com Iscas Steelfish\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-070"
  },
  {
    "date": "2026-11-21",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Lifestyle & Esporte",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nMetas de Pesca 2027: Qual Troféu Você Vai Buscar com a Steelfish?\n\nEspecial: Black Friday & Cyber Monday!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-071"
  },
  {
    "date": "2026-11-23",
    "dayOfWeek": "Segunda-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Performance & Ação",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nNavegando a 40 Milhas: O Conforto do Corta-Vento Fishing Company\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-072"
  },
  {
    "date": "2026-11-24",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Dicas Práticas",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nTroca Rápida de Garatéias com Alicate Split Ring: Passo a Passo\n\nContexto Especial: Black Friday & Cyber Monday!\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-073"
  },
  {
    "date": "2026-11-25",
    "dayOfWeek": "Quarta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Manutenção & Dicas",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nTroca de Garatéias: Como Reforçar sem Prejudicar o Nado da Isca\n\nEspecial: Black Friday & Cyber Monday!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-074"
  },
  {
    "date": "2026-11-26",
    "dayOfWeek": "Quinta-feira",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "feed",
    "pillar": "Segurança Náutica",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nSegurança Náutica: Flutuabilidade Impossível de Naufragar no Caiaque Titan\n\nDestaque: Black Friday & Cyber Monday!\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-075"
  },
  {
    "date": "2026-11-27",
    "dayOfWeek": "Sexta-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Campanha Comercial",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nBlack Friday Mathias: O Maior Desconto do Ano em Todo o Site\n\nAtenção: Black Friday & Cyber Monday!\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-076"
  },
  {
    "date": "2026-11-28",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nAtaque Visual: Slow Motion de Tucunaré Engolindo a Zara\n\nEspecial: Black Friday & Cyber Monday!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-077"
  },
  {
    "date": "2026-11-29",
    "dayOfWeek": "Domingo",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Acessórios Técnicos",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nBonés com Aba Anti-Reflexo: Melhor Visão dos Peixes na Água Rasa\n\nDestaque: Black Friday & Cyber Monday!\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-078"
  },
  {
    "date": "2026-11-30",
    "dayOfWeek": "Segunda-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Engenharia de Varas",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nPassadores de Zircônia vs Óxido de Alumínio: Entenda a Diferença\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-079"
  },
  {
    "date": "2026-12-01",
    "dayOfWeek": "Terça-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Equipamento",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nVara Rápida vs Moderada: Qual Escolher para Iscas de Hélice?\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-080"
  },
  {
    "date": "2026-12-02",
    "dayOfWeek": "Quarta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Manutenção & Dicas",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nLavagem e Cuidados: Como Manter a Proteção UV50+ Eterna na sua Camisa\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-081"
  },
  {
    "date": "2026-12-03",
    "dayOfWeek": "Quinta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Fotografia de Pesca",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nEstilo na Foto do Troféu: Valorize sua Captura com um Uniforme Impecável\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-082"
  },
  {
    "date": "2026-12-05",
    "dayOfWeek": "Sábado",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Aviso de Envios",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nDezembro em Alta: Garanta suas Iscas Antes do Recesso de Fim de Ano\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-083"
  },
  {
    "date": "2026-12-06",
    "dayOfWeek": "Domingo",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Técnica",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nCombinação Perfeita: Linha Multifilamento e Líder de Fluorocarbono\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-084"
  },
  {
    "date": "2026-12-07",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Campanha de Natal",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nPresente de Amigo Secreto do Pescador: Vales e Iscas Mathias\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-085"
  },
  {
    "date": "2026-12-08",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Campanha de Natal",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nPresente de Natal Útil: O Kit de Ferramentas Essencial da TR Fishing\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-086"
  },
  {
    "date": "2026-12-09",
    "dayOfWeek": "Quarta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Dicas de Pesca",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nAceleração no Final do Recolhimento: O Truque dos Guias\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-087"
  },
  {
    "date": "2026-12-10",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Leitura de Ambiente",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nLeitura de Água: Identificando Bicos de Pedra e Ilhas Submersas\n\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-088"
  },
  {
    "date": "2026-12-11",
    "dayOfWeek": "Sexta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Versatilidade",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nTreino e Pesca: A Roupa que Funciona no Caiaque e na Academia\n\nDestaque: Campanha de Natal!\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-089"
  },
  {
    "date": "2026-12-12",
    "dayOfWeek": "Sábado",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Design Exclusivo",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nCamuflagem Aquática: As Estampas Subaquáticas que Integram Você à Natureza\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-090"
  },
  {
    "date": "2026-12-13",
    "dayOfWeek": "Domingo",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "reels",
    "pillar": "Campanha de Natal",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nO Melhor Presente de Natal: Liberdade Absoluta na Água com seu Caiaque Titan\n\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-091"
  },
  {
    "date": "2026-12-14",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Ação & Esportividade",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nPescaria de Caiaque: Como Arremessar Sentado sem Perder Distância\n\nEspecial: Campanha de Natal!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-092"
  },
  {
    "date": "2026-12-15",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "feed",
    "pillar": "Revisão de Equipamentos",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nRevisão Geral de Fim de Ano: Deixe seus Equipamentos Prontos para as Férias\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-093"
  },
  {
    "date": "2026-12-17",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Acessórios",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nSnap Reforçado: Segurança Máxima na Batalha com o Troféu\n\nEspecial: Campanha de Natal!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-094"
  },
  {
    "date": "2026-12-18",
    "dayOfWeek": "Sexta-feira",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Performance Clima",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nChuva de Verão: Secagem em Minutos para Continuar a Batalha\n\nDestaque: Campanha de Natal!\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-095"
  },
  {
    "date": "2026-12-19",
    "dayOfWeek": "Sábado",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Lifestyle Campeão",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nSábado Premiado: A Roupa Oficial dos Campeões de Pesca Esportiva\n\nDestaque: Campanha de Natal!\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-096"
  },
  {
    "date": "2026-12-20",
    "dayOfWeek": "Domingo",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "feed",
    "pillar": "Logística de Férias",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nÚltima Semana de Envios de 2026: Despacho Imediato para suas Férias\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-097"
  },
  {
    "date": "2026-12-21",
    "dayOfWeek": "Segunda-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "reels",
    "pillar": "Férias de Verão",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nFérias no Lago: Comece o Ano Novo na Batida do Peixe!\n\nEspecial: Férias de Verão & Ano Novo!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-098"
  },
  {
    "date": "2026-12-22",
    "dayOfWeek": "Terça-feira",
    "time": "18:00",
    "brand": "TR Fishing",
    "theme": "tr_fishing",
    "format": "reels",
    "pillar": "Planejamento Técnico",
    "title": "TR Fishing",
    "seasonalHook": "",
    "caption": "[TR FISHING • DICA TÉCNICA]\n\nGuia Definitivo de Equipamentos para a Temporada de Verão 2027\n\nDica técnica direta ao ponto para elevar o nível da sua pescaria. O detalhe no nó, na calibragem e no equipamento é o que separa a perda do peixe do troféu no barco.\n\nConte com a TR Fishing para equipamentos precisos e soluções inteligentes.\nSiga @trfishingoficial.\n\n#trfishing #dicasdepesca #pescaesportiva #nofg #equipamentodepesca #eldoradopesca",
    "status": "planned",
    "id": "insta-104-099"
  },
  {
    "date": "2026-12-23",
    "dayOfWeek": "Quarta-feira",
    "time": "18:30",
    "brand": "Iscas Mathias",
    "theme": "iscas_mathias",
    "format": "reels",
    "pillar": "Comunidade & Fim de Ano",
    "title": "Iscas Mathias",
    "seasonalHook": "",
    "caption": "[ISCAS MATHIAS • CATÁLOGO & ISCAS]\n\nGratidão 2026: Milhares de Pedidos Entregues e Milhares de Peixes Fisgados\n\nCredibilidade, envio rápido e produtos selecionados a dedo para pescadores que buscam resultado garantido. Cada pedido é embalado com proteção máxima e despachado no mesmo dia.\n\nGaranta as suas iscas favoritas antes que esgotem.\nAcesse @iscasmathias e chame no WhatsApp de atendimento!\n\n#iscasmathias #iscasartificiais #pescaesportiva #lojadepesca #despachorapido #eldoradopesca",
    "status": "planned",
    "id": "insta-104-100"
  },
  {
    "date": "2026-12-24",
    "dayOfWeek": "Quinta-feira",
    "time": "18:30",
    "brand": "Steelfish",
    "theme": "steelfish",
    "format": "feed",
    "pillar": "Galeria de Troféus",
    "title": "Steelfish",
    "seasonalHook": "",
    "caption": "[STEELFISH • ALTA PERFORMANCE]\n\nTop 5 Capturas de Dezembro no Eldorado Lake com Steelfish\n\nEspecial: Campanha de Natal!\nNa pesca esportiva de alta performance, cada arremesso precisa ser cirúrgico. As iscas e carretilhas Steelfish entregam a estabilidade e o acabamento que o pescador exigente busca nos grandes lagos.\n\nDica prática: Garanta o recolhimento cadenciado e teste variações de velocidade no mesmo ponto.\n\nEquipamento oficial do Eldorado Lake.\nConfira o catálogo em @steelfish.oficial.\n\n#steelfish #pescaesportiva #tucunare #iscasartificiais #eldoradopesca #reelsdepesca",
    "status": "planned",
    "id": "insta-104-101"
  },
  {
    "date": "2026-12-25",
    "dayOfWeek": "Sexta-feira",
    "time": "19:30",
    "brand": "Titan Caiaques",
    "theme": "titan_caiaques",
    "format": "feed",
    "pillar": "Férias & Lifestyle",
    "title": "Titan Caiaques",
    "seasonalHook": "",
    "caption": "[TITAN CAIAQUES • ALTA PERFORMANCE]\n\nFérias no Lago: A Experiência Incomparável de Pescar a Poucos Centímetros da Água\n\nDestaque: Campanha de Natal!\nA verdadeira revolução na pesca em caiaque. Estabilidade que permite ficar em pé com total firmeza, sistema de propulsão a pedal silencioso e acabamento de padrão internacional.\n\nDescubra novos pontos de pesca inacessíveis para barcos comuns.\nConheça a linha completa em @titancaiaques.\n\n#titancaiaques #caiaquedepesca #pescadecaiaque #altaperformance #eldoradopesca #caiaqueiro",
    "status": "planned",
    "id": "insta-104-102"
  },
  {
    "date": "2026-12-26",
    "dayOfWeek": "Sábado",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "feed",
    "pillar": "Catálogo & Escolha",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nGuia de Tamanhos e Caimento Masculino e Feminino na Pesca\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-103"
  },
  {
    "date": "2026-12-27",
    "dayOfWeek": "Domingo",
    "time": "19:00",
    "brand": "Fishing Company",
    "theme": "fishing_company",
    "format": "reels",
    "pillar": "Fim de Ano & Natureza",
    "title": "Fishing Company",
    "seasonalHook": "",
    "caption": "[FISHING COMPANY • VISTA A MARCA]\n\nÚltimo Sábado do Ano: Celebre suas Conquistas na Natureza!\n\nConforto, proteção solar fator UV50+ e durabilidade extrema. Na represa de Foz do Areia o sol não perdoa: proteja sua saúde sem abrir mão da máxima respirabilidade.\n\nVista a marca que veste os pescadores mais exigentes do Brasil.\nDisponível na loja oficial @fishingcompany.\n\n#fishingcompany #camisadepesca #protecaouv #pescaesportiva #eldoradopesca #outdoorlife",
    "status": "planned",
    "id": "insta-104-104"
  }
];
