-- ==============================================================================
-- ELDORADO PESCA & LAKE - SUPABASE POSTGRESQL SCHEMA COMPLETO
-- Execute este script no "SQL Editor" do seu painel Supabase (supabase.com)
-- ==============================================================================

-- 1. Configurações Globais (settings)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabela de Rifas / Ações (raffles)
CREATE TABLE IF NOT EXISTS public.raffles (
    id TEXT PRIMARY KEY,
    number TEXT,
    title TEXT NOT NULL,
    subtitle TEXT,
    price_per_number NUMERIC(10, 2) DEFAULT 0,
    total_numbers INTEGER NOT NULL,
    reservation_timeout_hours INTEGER DEFAULT 24,
    pix_key TEXT,
    pix_owner TEXT,
    shipping_note TEXT,
    live_draw_note TEXT,
    private_contact TEXT,
    rules TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Números das Rifas (raffle_numbers)
CREATE TABLE IF NOT EXISTS public.raffle_numbers (
    raffle_id TEXT NOT NULL REFERENCES public.raffles(id) ON DELETE CASCADE,
    num INTEGER NOT NULL,
    name TEXT DEFAULT '',
    status TEXT DEFAULT 'available',
    reserved_at TIMESTAMP WITH TIME ZONE,
    paid_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (raffle_id, num)
);

-- 4. Prêmios Definidos por Rifa (raffle_prizes)
CREATE TABLE IF NOT EXISTS public.raffle_prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raffle_id TEXT NOT NULL REFERENCES public.raffles(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    description TEXT NOT NULL,
    winner_number INTEGER,
    winner_name TEXT
);

-- 5. Vales e Prêmios / Haver / Trocas (vales_prizes)
CREATE TABLE IF NOT EXISTS public.vales_prizes (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    type TEXT NOT NULL, -- 'dual_choice', 'vale_compras', 'premio_fisico'
    raffle_ref TEXT,
    date_won DATE DEFAULT CURRENT_DATE,
    initial_amount NUMERIC(10, 2) DEFAULT 0,
    current_balance NUMERIC(10, 2) DEFAULT 0,
    description TEXT NOT NULL,
    status TEXT NOT NULL, -- 'pending_choice', 'pending_schedule', 'scheduled', 'active', 'pending_pickup', 'delivered'
    delivered_at DATE,
    notes TEXT,
    exchanged_item TEXT,
    difference_paid NUMERIC(10, 2) DEFAULT 0,
    exchange_notes TEXT,
    exchanged_at DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Transações e Baixas de Vales-Compras (vale_transactions)
CREATE TABLE IF NOT EXISTS public.vale_transactions (
    id TEXT PRIMARY KEY,
    vale_id TEXT NOT NULL REFERENCES public.vales_prizes(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    item TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    remaining_balance NUMERIC(10, 2) NOT NULL,
    registered_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. Agenda de Pescaria - Eldorado Lake (fishing_bookings)
CREATE TABLE IF NOT EXISTS public.fishing_bookings (
    id TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_phone TEXT,
    booking_type TEXT DEFAULT 'direct', -- 'direct', 'raffle_prize'
    raffle_ref TEXT,
    prize_id TEXT,
    start_date DATE NOT NULL,
    end_date DATE,
    dates JSONB, -- Array de datas para reservas flexíveis
    total_days INTEGER DEFAULT 1,
    raffle_days INTEGER DEFAULT 1,
    extra_days INTEGER DEFAULT 0,
    package_name TEXT,
    structure_type TEXT DEFAULT 'dupla',
    fishermen_count INTEGER DEFAULT 2,
    boats_count INTEGER DEFAULT 1,
    kayaks_count INTEGER DEFAULT 0,
    custom_structure TEXT,
    total_amount NUMERIC(10, 2) DEFAULT 0,
    deposit_amount NUMERIC(10, 2) DEFAULT 0,
    remaining_amount NUMERIC(10, 2) DEFAULT 0,
    payment_status TEXT DEFAULT 'pending', -- 'pending', 'deposit_paid', 'paid'
    payment_method TEXT DEFAULT 'Pix',
    notes TEXT,
    guide_name TEXT DEFAULT 'Thiago Witeck',
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'cancelled'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. Locações do Rancho Eldorado (rancho_bookings)
CREATE TABLE IF NOT EXISTS public.rancho_bookings (
    id TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_phone TEXT,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    total_days INTEGER DEFAULT 1,
    guests_count INTEGER DEFAULT 2,
    total_amount NUMERIC(10, 2) DEFAULT 0,
    deposit_amount NUMERIC(10, 2) DEFAULT 0,
    remaining_amount NUMERIC(10, 2) DEFAULT 0,
    payment_status TEXT DEFAULT 'pending', -- 'pending', 'deposit_paid', 'paid'
    payment_method TEXT DEFAULT 'Pix',
    notes TEXT,
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'cancelled'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. Folha e Ponto do Eduardo (eduardo_work_days)
CREATE TABLE IF NOT EXISTS public.eduardo_work_days (
    date DATE PRIMARY KEY,
    type TEXT NOT NULL, -- 'full', 'half', 'off'
    hours_weight NUMERIC(4, 2) DEFAULT 1.0,
    amount_due NUMERIC(10, 2) DEFAULT 0,
    notes TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- ÍNDICES PARA ALTA PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_raffle_numbers_raffle_id ON public.raffle_numbers(raffle_id);
CREATE INDEX IF NOT EXISTS idx_vales_customer_name ON public.vales_prizes(customer_name);
CREATE INDEX IF NOT EXISTS idx_fishing_start_date ON public.fishing_bookings(start_date);
CREATE INDEX IF NOT EXISTS idx_rancho_check_in ON public.rancho_bookings(check_in_date);

-- ==============================================================================
-- ATIVAR REALTIME DO SUPABASE (Sincronização em tempo real entre dispositivos)
-- ==============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.settings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.raffles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.raffle_numbers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.vales_prizes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.vale_transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.fishing_bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.rancho_bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.eduardo_work_days;

-- ==============================================================================
-- POLÍTICAS DE ACESSO (Row Level Security - RLS)
-- Permite leitura e escrita pelo app através da chave pública anônima
-- ==============================================================================
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raffles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raffle_numbers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raffle_prizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vales_prizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vale_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fishing_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rancho_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eduardo_work_days ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso Total Settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Raffles" ON public.raffles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Raffle Numbers" ON public.raffle_numbers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Raffle Prizes" ON public.raffle_prizes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Vales" ON public.vales_prizes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Transactions" ON public.vale_transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Fishing" ON public.fishing_bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Rancho" ON public.rancho_bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Eduardo" ON public.eduardo_work_days FOR ALL USING (true) WITH CHECK (true);
